name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build Go
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Check out libgit2
      uses: actions/checkout@v2
      with:
        repository: 'libgit2/libgit2'
        ref: 'v1.0.1'
        path: libgit2

    - name: Fetch libgit2 dependencies
      run: |
        sudo apt-get install libmbedtls-dev libssh2-1-dev zlib1g-dev libhttp-parser-dev

    - name: Build libgit2
      run: |
        cd libgit2 && mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr
        cmake --build .
        sudo cmake --build . --target install

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        go build -v ./...

    - name: Test
      run: |
        go test -v ./...
